---
- name: install pilotgo-server
  dnf: 
    name: PilotGo-server
    state: present
  register: pilotgo_info
  ignore_errors: yes
- name: exit when pilotgo-server fail install
  fail:  
    msg: 'dnf install PilotGo-server failed'
  when: pilotgo_info.rc != 0
- name: change PilotGo config
  template: src=templates/pilotgo/config_server.yaml.j2 dest={{ pilotgo_config }}