---
- name: install mysql for PilotGo platform
  hosts: mysql
  become: yes
  become_user: root

  roles: 
    - mysql
  tasks: 
  - name: Ensure a user can connect from a specific host  
    mysql_user:  
      name: root  
      host: '%'  
      password: '{{ mysql_password }}'  
      priv: '*.*:ALL,GRANT'  
      state: present
- name: install redis for PilotGo platform
  hosts: reids
  become: yes
  become_user: root

  roles: 
    - redis
  tasks: 
  - name: change protected mode
    lineinfile: 
      path: /etc/redis/redis.conf
      regexp: '^#?protected-mode'
      line: 'protected-mode no'
      backrefs: yes
  - name: restart redis service
    service: 
      name: redis
      state: restarted
- name: install neo4j
  hosts: neo4j
  remote_user: root

  roles: 
    - neo4j
- name: install pserver PilotGo platform
  hosts: pilotgo
  become: yes
  become_user: root

  roles: 
    - pilotgo
- name: install agent for PilotGo platform
  hosts: pilotgo-agent
  become: yes
  become_user: root

  roles: 
    - pilotgo-agent
- name: install plugin topology for PilotGo platform
  hosts: topo
  become: yes
  become_user: root

  roles: 
    - topo
- name: install topology agent for PilotGo platform
  hosts: topo-agent
  become: yes
  become_user: root

  roles: 
    - topo-agent